export const string = {
  welcom: 'WELCOME TO APP',
  login: 'Login',
  Forget: "Forget password ?",
  or: 'Or',
  Didn: "Didn’t have account ? ",
  Signup: 'Sign up',
  already: 'Already have an account ? ',
  loginrsc: 'Login Now',
  OTPVeri: "OTP Verification",
  Enteryour: "Enter your OTP code here",
  received: "Don’t received code ? ",
  Resend: 'Resend',
  Verify: 'Verify',
  hii: 'Hii',
  userName: "Dinesh kumar",
  West: "West Mambalam,",
  YourSubscription: "Your Premium Subscription Plan\nExpire in Mar 12",
  Premium: 'Subscription plan ',
  all: 'All',
  rent: 'Rent',
  Plot: 'Plot/Flat',
  individual: 'Individual Home',
  rent: 'Rent',
  Individualhouse: '( Individual house )',
  Popular: 'Popular Property',
  Viewall: 'View all',
  Sale: 'Sale',
  Individual: ' ( Individual house )',
  Westtwo: "West Mambalam,",
  Today: 'Most visit property',
  TodayDEA: 'Today Details',
  PropertyDetails: 'Property Details',
  divina: 'Divina House',
  Description: 'Description',
  dish: 'A property description is the written part of the real estate listing that describes the details and noteworthy features of the home. As potential buyers read real estate listings, a well-written description will help pique their interest',
  Address: "Address",
  addre: "No 3/1, 1st Street West Mambalam, Chennai - 600033",
  PropertyFt: 'Property Sq . Ft',
  HouseSpacing: "House Spacing",
  IndividualhouseBHK: "Individual house, ( 3 BHK ) ",
  FlatFacing: "Flat Facing",
  NorthFacingArea: "North Facing Area",
  Furnishing: 'Furnishing',
  Yes: 'Yes',
  AdvertisementID: "Advertisement ID",
  DH456KD897: "#DH456KD897",
  EnquiryForm: "Enquiry Form",
  Name: "Name",
  Mobilenumber: 'Mobile number',
  WhatsAppnumber: "WhatsApp number",
  EmailID: "E-mail ID",
  Message :'Message ',
  Enquirynow: "Enquiry now",
  Profile: "Profile",
  dinesh: 'Dinesh Kumar',
  Notifications: "Notifications",
  PaymentHistory: 'Payment History',
  MyPropertydetails: "My Posted Details",
  TermsandConditions: "Terms and Conditions",
  Privacypolicy: "Privacy policy ",
  Mydetails: "My details",
  Address: 'Address',
  Save: 'Save',
  Dinesh: "Dinesh",
  new: 'new',
  Lorem: "Lorem Ipsum has been the industry's standard dummy text ever since",
  PaymentHistory: "Payment History",
  KaviyaAnjali: 'Kaviya Anjali',
  Sabitha: "Sabitha",
  Sanjaykumar: "Sanjay kumar",
  Dhanush: "Dhanush",
  ShivaKarthikeyan: 'Shiva Karthikeyan',
  Sowmiya: "Sowmiya",
  Individual: 'Individual  (3 BHK)',
  AnnaNagar: 'Anna Nagar',
  Flat: 'Flat',
  Renthouse: "Rent house",
  Salehouse: 'Sale house',
  SelectProperty: 'Select Property Type',
  EnteryourPricing: 'Enter your Pricing',
  SelectyourState: 'Select your State',
  yourDistrict: 'Select your District',
  SelectyourCity: 'Select your City',
  SelectyourArea: 'Select your Area',
  Furnishing: "Furnishing",
  Individualtwo: 'Individual ',
  BHK: '(3 BHK)',
  ok: 'OK',
  Whydoweuseit: "Why do we use it?",
  discrip: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  privacy: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
  Maksubscription: "Make Subscription To Enjoy Your Plan ",
  Basic: 'Basic',
  Premium2: "Premium",
  SelectDistrict:'Listed by',
  Selectstate:'Super Buildup area(SQ.FT)',
  PropertyMethods:'Bedrooms',
  Bathrooms:'Bathrooms',
  Selectcity:'Bachelors Allowed',
  longestablishedfact: 'long established fact ',
  opposedtousing: "opposed to using",
  webpageeditors: 'web page editors',
  onlyfivecenturies: "only five centuries",
  Subscribe: 'Subscribe',
  PERMONTH: "PER MONTH",
  addvance: 'Addvance',
  RentProperty: "Sale ( Houses & Apartment )",
  PropertyName: "Property Name",
  Mobilenumber: "Mobile number",
  Description: "Description",
  PropertyType: "Property Type",
  Maintenance: "Maintenance ( monthly )",
  AreaLocation: "Area Location",
  Address: 'Address',
  tottal: "Total Floors",
  Furnished: "Furnished",
  AgeofBuilding: "Floor No",
  Value: "Building Facing",
  Commission: "Amount",
  BuildingFacing: "Car parking",
  ImageUpload: "Image Upload",
  VideoUpload: "Video Upload",
  Submit: "Submit",
  FlatFacing: "Flat Facing",
  MakesubscriptionPlan: 'Make subscription Plan',
  ShareyourFeedback: 'Share your Feedback',
  PopularProperty:'Popular  Property', 
  logout:'LogOut',
  ForgetPassword:"Forgot Password",
  dontworry: "Don't worry! Please enter the email\naddress linked with your account.",
  Viewnow:'View now', 
  bhk:'2BHK',
  ListofProperty:"List of Property",
  rensandsales:'Rent & Sale',
  Enquirylist:"Enquiry list",
  Postenquiry:"Post enquiry",
  Propertyenquiry:'Property enquiry',
  rajuhouse:"Raju House",
  anna:'Anna Nagar',
  moreview:'View more',
  name:'Name',
  mobilenumber:'Mobile number',
  email:'E-mail Id',
  whatsapp:'Whatsapp number',
  message:'Message',
  messtext:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
  SubscriptionHistory:'Subscription History',
  New:'New',
  Basic:'Basic Subscription plan',
  Startingdate:"Starting date",
  Adsno:'Ads no',
  Enddate:'End date',
  Expired:"Expired",
  Premium:'Premium Subscription plan',
  Renewal:'Renewal',
  Proplan:'Pro Subscription plan',
  Premiumscriptionplan:'Premium Subscription plan',
  Individualmy: 'Individual (3 BHK)',
  Status:'Status',
  Soldout:'Sold out',
  ads:'Ads', on:'On', off:'Off',
  MyPropertyd: "My Property List",
  UseYourLocation:'Use Your Location',
  Usecurrentlocation:'Use current location',
  Cancel:'Cancel',
  ok:'OK',
  SelectCategories:'Select Categories',
  Property:'Property',
  Listed:'Listed by',
  Categories:'Categories',
  carpet:'Carpet area SQ.FT',
  RentApartmen:"Rent ( Houses & Apartment )",
  ConstructionStatus:'Construction Status',
  landplot:'Land & Plot',
  plotarea:'Plot area',
  length:'Langth',
  breadth:'Breadth',
  RentOffice :"Rent ( Shop & Office )",
  Washrooms:'Wash rooms',
  PGHouse:'PG & Guest House',
  SaleShopOffice:'Sale ( Shop & Office )',
  roomtypes:'Room Types',
  MealsIncluded:'Meals Included',
  bikes:'Bikes',
  UploadMotorcycle:"Upload Motorcycle",
  BrandModel:'Brand / Model',
  year:'Year',
  KmDiven:'Km Driven',
  AdTile:'Ad Title',
  amo:'Amount',
  uploadBicycles:'Upload Bicycles',
  ByPrice:"By Price",
  Choosefrobelow:"Choose from options below",
  Clearall:'Clear all',
  Apply:'Apply',
  Freshrecommendation:"Fresh recommendation",
  ap:'All Product',
  Choosearangbelow:"Choose a range below",
  POPULARBRANDS:'POPULAR BRANDS',
  allbranda:'All BRANDS',
  AllModels:'ALL MODELS',
  VERIFIEDSELLER:'VERIFIED SELLER',Description:'Description',
  TechnicalDetails:'Technical Details',
  RecommendedLaptop:'Recommended Laptop',
  Electronics:'Electronics',
  UploadElectronics:'Upload Electronics',
  Modelname:'Model Name',
  modelyear:'Model Year',
  amount:'Amount',
  location:'Location',
  NumberofOwner:'Number of Owner',
  ProcessorBrand:'Processor Brand',
  ProcessorTypes:"Processor Types",
  ProcessorSpeed:'Processor Speed',
  ProcessorCounts:'Processor Counts',
  RamSize:'Ram Size',
  MaximumMemorySupported:'Maximum Memory Supported',
  HardDriveSize:'Hard Drive Size',
  HardDiskDescription:'Hard Disk Description',
  HardDrive:'Hard Drive',
  HardDiskRotationalSpeed:'Hard Disk Rotational Speed',
  AdTitle:'Ad Title',
  RecommendedBike:'Recommended Bike',
  recommendedtext:'Recommended Cars',
   RecommendedProparty:'Recommended Property',
  uploadcar:'Upload Car',
  brand:'Brand',
  fuel:'Fuel',
  Transmission:'Transmission',
  KMDrive:'KM Drive',
  noofOwners:'No Of Owners',
  adtitle:'AD Title',
  location :'Location '
  


  
}